#pragma once

#define PERMISSIVE_HOLD
#define CHORDAL_HOLD
#define TAPPING_TERM 190
#define RGB_MATRIX_TIMEOUT 120000
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_GRADIENT_UP_DOWN
#define RGB_MATRIX_DEFAULT_HUE 200
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL 160
#define RGB_MATRIX_DEFAULT_SPD 0
