// Copyright 2026 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | mono2
//    output | modifiers
//    input  | shift.png

#pragma once

#include <qp.h>

extern const uint32_t gfx_shift_length;
extern const uint8_t  gfx_shift[273];
